---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/para-agencias
    - /bin/mkdir -p $DEPLOYPATH/assets
    - /bin/cp -f index.html $DEPLOYPATH/
    - /bin/cp -Rf assets/. $DEPLOYPATH/assets/
